### PR TITLE
Force PDO Connection for mysqli DSN by 'cleaning' the connection string

### LINKED ISSUE #44: slimdump will fail when provinding a mysqli://... DSN
This will make Doctrine DBAL choose the `mysqli` driver (https://www.doctrine-project.org/projects/doctrine-dbal/en/2.7/reference/configuration.html#driver). 

Further down the road, this will lead to an `PHP Fatal error:  Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliConnection::setAttribute() in /usr/share/slimdump/src/Webfactory/Slimdump/Database/Dumper.php on line 154`.

The reason is we're trying to use an unbuffered connection, so that we can flush large datasets out to disk immediately, without loading them into memory first.

```php
$wrappedConnection = $db->getWrappedConnection();
$wrappedConnection->setAttribute(\PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, false);
```

This is possible with PDO connections only, as the `setAttribute()` method is inherited from `\PDO` in `Doctrine\DBAL\Driver\PDOConnection`.

Solutions: Either fail with a nice error message, or force DBAL to use the PDO driver in any case.

### PR DESCRIPTION
**Pull request by xkons**
I didn't want to give up the parsing of the DSN string by the DriverManager so I chose to replace the 'mysqli://' in the connection string with 'mysql://' if it exists, this way we should always end up with a PDO Connection.

If we would do the parsing ourselves then we could skip the 'url' Parameter in DriverManager::getConnection($params).

Any connection information inside $params['url'] will always precede other parameters, see https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/DriverManager.php#L400

Fixes #44 

DBAL Docs on creating a Connection: https://www.doctrine-project.org/projects/doctrine-dbal/en/2.7/reference/configuration.html

### CODE REVIEW

File: src/Webfactory/Slimdump/SlimdumpCommand.php [hunk 1]
```diff
@@ -56,10 +58,16 @@ protected function execute(InputInterface $input, OutputInterface $output)
...
-            return \Doctrine\DBAL\DriverManager::getConnection(
-                array('url' => $dsn, 'charset' => 'utf8', 'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver')
+            /**
+             * a dsn string containing mysqli will result in the DriverManager creating a MysqliConnection but we need PDO
+             * @see DriverManager::parseDatabaseUrlScheme()
+             */
+            $mysqliIndependentDsn = str_replace('mysqli://', 'mysql://', $dsn);
+
+            return DriverManager::getConnection(
+                array('url' => $mysqliIndependentDsn, 'charset' => 'utf8', 'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver')
```
Comment (mpdude) [inline src/Webfactory/Slimdump/SlimdumpCommand.php]: `'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver'` is actually pointless, it will be overridden as well when the URL is parsed

File: src/Webfactory/Slimdump/SlimdumpCommand.php [hunk 2]
```diff
@@ -56,10 +58,16 @@ protected function execute(InputInterface $input, OutputInterface $output)
     private function connect($dsn)
     {
         try {
-            return \Doctrine\DBAL\DriverManager::getConnection(
-                array('url' => $dsn, 'charset' => 'utf8', 'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver')
+            /**
```
Comment (mpdude) [inline src/Webfactory/Slimdump/SlimdumpCommand.php]: This need not be a docblock here

File: src/Webfactory/Slimdump/SlimdumpCommand.php [hunk 3]
```diff
@@ -56,10 +58,16 @@ protected function execute(InputInterface $input, OutputInterface $output)
...
+             * a dsn string containing mysqli will result in the DriverManager creating a MysqliConnection but we need PDO
+             * @see DriverManager::parseDatabaseUrlScheme()
+             */
+            $mysqliIndependentDsn = str_replace('mysqli://', 'mysql://', $dsn);
```
Comment (mpdude) [inline src/Webfactory/Slimdump/SlimdumpCommand.php]: Would it be more cautious to use a `preg_replace('_^mysqli://_', ...)`?

Comment (xkons) [reply src/Webfactory/Slimdump/SlimdumpCommand.php]: Ah yes I like that beginning of string check!

File: src/Webfactory/Slimdump/SlimdumpCommand.php (hunk 2 above)
Comment (mpdude) [reply src/Webfactory/Slimdump/SlimdumpCommand.php]: ✔
