### PR TITLE
Fill in dummy types to deal with DC2:... column comments

### LINKED ISSUE #96: Unable to deal with custom Doctrine types (Case 167398)
Assume your database contains a table with a definition like so:

```
CREATE TABLE `test` (
  `some_col` int NOT NULL COMMENT '(DC2Type:some_type)'
)
```

In your application, you may have configured Doctrine with some special (custom) mapping type, thus the comment `(DC2Type:some_type)`. 

When trying to dump this database, `slimdump` fails with an exception when trying to load the schema information, since the `some_type` type is not known to DBAL. 

It should not be necessary to configure this type either; in fact, we (probably) don't care about types that much, we just need to decide whether or not we're dealing with BLOB values.

Probably we need to come up with a clever way of how/when to register placeholder types dynamically?

### PR DESCRIPTION
**Pull request by mpdude**
We're using the `SchemaManager` to simplify listing tables, views and so on. But, the information provided by it also includes the DBAL types used for columns, and that information may be parsed from column comments in the database.

The problem is that a table definition like so:

```sql
CREATE TABLE `test` (
  `some_col` int NOT NULL COMMENT '(DC2Type:some_type)'
)
```

... `slimdump` fail fail with an exception because it does not know about the `some_type`. This type may be available and defined in your application, but we cannot put it into the `slimdump` command.

Now, in fact, we don't care about the type and its conversion capabilities at all. So, this PR adds a runtime "just in type" registration of a `DummyType` that serves as a placeholder to avoid issues when loading the schema.

Fixes #96.

### CODE REVIEW

File: src/Webfactory/Slimdump/Doctrine/DummyType.php [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+use Doctrine\DBAL\Types\Type;
+use LogicException;
+
+class DummyType extends Type
+{
+    public const NAME = 'dummy_type';
+
+    public function convertToPHPValue($value, AbstractPlatform $platform)
+    {
+        throw new LogicException('this should not be called in the first place');
```
Comment (janopae) [inline src/Webfactory/Slimdump/Doctrine/DummyType.php:15]: Maybe we could have a better description in this file on why it exists. Maybe these error messages would be a good place for such a description.

It could be something like `This Doctrine type assumes that the types won't be used  to convert any data – it's just there to allow the rest of DBAL's functionality to work without throwing errors`. What do you think?

Comment (mpdude) [reply src/Webfactory/Slimdump/Doctrine/DummyType.php:15]: #109
